---
title: "Treatments for Alzheimer's disease"
author:
  - name: Bertil Gustav
date: 2023-09-09
output:
  distill::distill_article:
    self_contained: false
---



```{css, echo = FALSE}
body {
position: relative;
left: -350px;
width: 1800px
}

h1 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}


h3 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

d-article h3 {
    margin-top: 0.3rem;
    margin-bottom: 0em;
}

ul {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

p {
text-indent: 0;
padding: -1;
border: 0px;
width: 1200px;
margin-top: 1rem;
}

d-article li {
    margin-top: 0em;
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}

d-article p, d-article ul, d-article ol, d-article blockquote {
    margin-top: 1;
    margin-bottom: 0em;
    margin-left: 0;
    margin-right: 0;
}
```


### **Important terms**
- **Sum of boxes of the Clinical Dementia Rating Scale (CDR-SB)**:
- **Amyloid-related imaging abnormalities (ARIA)**:
- **Aducanumab**: [Trial protocol](https://cdn.jamanetwork.com/ama/content_public/journal/neur/938841/noi210073supp1_prod_1641404428.54093.pdf?Expires=1697337457&Signature=OpYtB7qcvcsk8Pt3pGKQIFPCGXJTZpre9j8I2skXdnKgY3IwPM07SuvlMw2-SqNmBvH~gJ2K~QrRy3WegCe9g5WyW7WGPeWCV1CSn~gspufoPDzVn79s9mccBasw5QW0jcLOvzbJztFqSUqpAr1ND~sUzDtcuDdSrs7s9EgOc8rm0Eze-L0O~eFh4Y1Fv8CFZm2XdnmVaR7MUJtYg~c9e8Q7x3yXwO8vw01KbCXYiJtCq~8ZKs0A8RiYqAiLQZ1oz5OU8DV88C9dyNx3gOOwY1i4AGRv6nFEKDhmBPnj7FiEDuEtBiLOSFfl0ppVC7kCy6MJryklZHThnmbIJWbJ8Q__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA){target="_blank"}
- **Lecanemab (CLARITY-AD study, phase 3)**: 
  * People aged 50-90 years with MCI and mild-stage dementia due to AD, with amyloid pathology confirmed by PET scans or CSF testing.
  * 18-month double-blinded, placebo-controlled, intravenous infusion every 2 weeks.
  * CDR-SB declined by 1.66 and 1.21 points (0.45 difference) in the treated and placebo receivers.
  * homozygous APOE e4 allele carriers, people with cerebral amyloid angiography, and people taking anticoagulant drugs. 
- **Denanemab (TRAILBLAZER-ALZ 2 study, phase 3, global trial)**: 
  * MCI and mild-stage dementia due to AD, with amyloid and tau pathology confirmed by PET scans, people aged 85 years and above were excluded.
  * 18-month double-blinded, placebo-controlled, intravenous infusion every 4 weeks.
  * CDR-SB declined by 1.72 and 2.42 points (0.7 difference) in the treated and placebo receivers; 1/4-1/2 year longer stable status; 18% more people with Donanemab stayed stable on CDR-SB than with placebo at one year.
  * homozygous APOE e4 allele carriers, people with cerebral amyloid angiography, and people taking anticoagulant drugs. <br>
<br>

### **Remaining questions**
1. Will future maintenance doses be needed?
2. What are the long-term effects?<br>
<br>


### **Affected stakeholders**
- Patients and caregivers
- Primary care clinics-early detection of AD
- Specialty dementia clinics-diagnose AD and other types of dementia
- Emergency departments and radiologists<br>
<br>





### **Reference:**<br>
Widera EW, Brangman SA, Chin NA. Ushering in a New Era of Alzheimer Disease Therapy. JAMA. 2023 Aug 8;330(6):503-504.<br>

Schneider LS. Viewpoint: When It Comes to Lecanemab (and Donanemab), How Might We Think about 'Reasonable and Necessary'? J Prev Alzheimers Dis. 2023;10(3):342-343.<br> 

van Dyck CH, Swanson CJ, Aisen P, Bateman RJ, Chen C, Gee M, Kanekiyo M, Li D, Reyderman L, Cohen S, Froelich L, Katayama S, Sabbagh M, Vellas B, Watson D, Dhadda S, Irizarry M, Kramer LD, Iwatsubo T. Lecanemab in Early Alzheimer's Disease. N Engl J Med. 2023 Jan 5;388(1):9-21.<br>

Sims JR, Zimmer JA, Evans CD, Lu M, Ardayfio P, Sparks J, Wessels AM, Shcherbinin S, Wang H, Monkul Nery ES, Collins EC, Solomon P, Salloway S, Apostolova LG, Hansson O, Ritchie C, Brooks DA, Mintun M, Skovronsky DM; TRAILBLAZER-ALZ 2 Investigators. Donanemab in Early Symptomatic Alzheimer Disease: The TRAILBLAZER-ALZ 2 Randomized Clinical Trial. JAMA. 2023 Aug 8;330(6):512-527.<br>

Cummings J, Apostolova L, Rabinovici GD, Atri A, Aisen P, Greenberg S, Hendrix S, Selkoe D, Weiner M, Petersen RC, Salloway S. Lecanemab: Appropriate Use Recommendations. J Prev Alzheimers Dis. 2023;10(3):362-377.<br>

Manly JJ, Deters KD. Donanemab for Alzheimer Disease-Who Benefits and Who Is Harmed? JAMA. 2023 Aug 8;330(6):510-511.<br>

Atwood CS, Perry G. Playing Russian Roulette with Alzheimer's Disease Patients: Do the Cognitive Benefits of Lecanemab Outweigh the Risk of Edema, Stroke and Encephalitis? J Alzheimers Dis. 2023;92(3):799-801.<br>

Thambisetty M, Howard R. Lecanemab and APOE Genotyping in Clinical Practice-Navigating Uncharted Terrain. JAMA Neurol. 2023 May 1;80(5):431-432.<br>

Rashad A, Rasool A, Shaheryar M, Sarfraz A, Sarfraz Z, Robles-Velasco K, Cherrez-Ojeda I. Donanemab for Alzheimer's Disease: A Systematic Review of Clinical Trials. Healthcare (Basel). 2022 Dec 22;11(1):32.<br>

Burke JF, Kerber KA, Langa KM, Albin RL, Kotagal V. Lecanemab: Looking Before We Leap. Neurology. 2023 Jul 21:10.1212/WNL.0000000000207505.<br>

McDade E, Cummings JL, Dhadda S, Swanson CJ, Reyderman L, Kanekiyo M, Koyama A, Irizarry M, Kramer LD, Bateman RJ. Lecanemab in patients with early Alzheimer's disease: detailed results on biomarker, cognitive, and clinical effects from the randomized and open-label extension of the phase 2 proof-of-concept study. Alzheimers Res Ther. 2022 Dec 21;14(1):191.<br>


Gueorguieva I, Willis BA, Chua L, Chow K, Ernest CS, Shcherbinin S, Ardayfio P, Mullins GR, Sims JR. Donanemab Population Pharmacokinetics, Amyloid Plaque Reduction, and Safety in Participants with Alzheimer's Disease. Clin Pharmacol Ther. 2023 Jun;113(6):1258-1267.<br>


Gueorguieva I, Willis BA, Chua L, Chow K, Ernest CS 2nd, Wang J, Shcherbinin S, Sims JR, Chigutsa E. Donanemab exposure and efficacy relationship using modeling in Alzheimer's disease. Alzheimers Dement (N Y). 2023 Jun 28;9(2):e12404.<br>


Wessels AM, Dennehy EB, Dowsett SA, Dickson SP, Hendrix SB. Meaningful Clinical Changes in Alzheimer Disease Measured With the iADRS and Illustrated Using the Donanemab TRAILBLAZER-ALZ Study Findings. Neurol Clin Pract. 2023 Apr;13(2):e200127.<br>







