---
title: "Vascular aging"
author:
  - name: Bertil Gustav
date: 2023-09-09
output:
  distill::distill_article:
    self_contained: false
---


```{css, echo = FALSE}
body {
position: relative;
left: -350px;
width: 1800px
}

h1 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}


h3 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

ul {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

p {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}
```


### **Terminology**
- **Vascular aging:**
- **Artherosclerosis:**
- **Arterial stiffness:**

### **Consequences of vascular aging**
- **Cardiovascular diseases:**
- **Cognitive dysfunction:**
- **Sarcopenia:**

### **How to prevent and decelerate vascular aging**


**Reference:**<br>
Nilsson PM, Boutouyrie P, Laurent S. Vascular aging: A tale of EVA and ADAM in cardiovascular risk assessment and prevention. Hypertension. 2009 Jul;54(1):3-10.<br>

Nilsson PM. Hemodynamic Aging as the Consequence of Structural Changes Associated with Early Vascular Aging (EVA). Aging Dis. 2014 Apr 1;5(2):109-13.<br>

Nilsson PM. Early Vascular Aging in Hypertension. Front Cardiovasc Med. 2020 Feb 4;7:6.<br>

Nilsson PM. Early vascular aging (EVA): consequences and prevention. Vasc Health Risk Manag. 2008;4(3):547-52.<br>

Jeon YK, Shin MJ, Saini SK, Custodero C, Aggarwal M, Anton SD, Leeuwenburgh C, Mankowski RT. Vascular dysfunction  as a potential culprit of sarcopenia. ExpGerontol. 2021 Mar;145:111220. doi: 10.1016/j.exger.2020.111220<br>

He N, Zhang Y, Zhang L, Zhang S, Ye H. Relationship Between Sarcopenia and Cardiovascular Diseases in the Elderly: An Overview. Front Cardiovasc Med. 2021 Dec 9;8:743710. doi: 10.3389/fcvm.2021.743710<br>

Banks NF, Rogers EM, Church DD, Ferrando AA, Jenkins NDM. The contributory role of vascular health in age-related anabolic resistance. J Cachexia Sarcopenia Muscle. 2022 Feb;13(1):114-127. doi: 10.1002/jcsm.12898.<br>

Mistriotis P, Andreadis ST. Vascular aging: Molecular mechanisms and potential treatments for vascular rejuvenation. Ageing Res Rev. 2017 Aug;37:94-116. doi: 10.1016/j.arr.2017.05.006.<br>

Naoyuki Hayashi, Chapter 11 - Vascular aging and sarcopenia: Interactions with physiological functions during exercise, Editor(s): Kunihiro Sakuma, Sarcopenia, Elsevier, 2021, Pages 249-265, ISBN 9780128221464, https://doi.org/10.1016/B978-0-12-822146-4.00012-0.<br>