---
title: "Cost-effectiveness of treatments for Alzheimer's disease"
author:
  - name: Bertil Gustav
date: 2023-09-09
output:
  distill::distill_article:
    self_contained: false
---



```{css, echo = FALSE}
body {
position: relative;
left: -350px;
width: 1800px
}

h1 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}


h3 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

d-article h3 {
    margin-top: 0.3rem;
    margin-bottom: 0em;
}

ul {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

p {
text-indent: 0;
padding: -1;
border: 0px;
width: 1200px;
margin-top: 1rem;
}

d-article li {
    margin-top: 0em;
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}

d-article p, d-article ul, d-article ol, d-article blockquote {
    margin-top: 1;
    margin-bottom: 0em;
    margin-left: 0;
    margin-right: 0;
}
```

### **Stakeholders**
- Patients
- Healthcare providers: physicians, nurses, and other healthcare professionals 
- Policymakers and government agencies
- Healthcare payers: public and private payers
- Health economists and researchers
- Pharmaceutical and medical device manufacturers<br>
<br>

### **Cost component**
- Direct Medical Costs
  * The medicine itself, infusion supplies, services, etc
  * Genotyping cost (e.g., APOE)??
  * Monitoring: MRI scans to assess ARIA, PET scans to assess amyloid clearance
  * Adverse event-associated costs (e.g., hospitalization), potential effects on cormorbidities?

- Indirect Medical Costs
  * Costs in specialised patient care or nursing homes
  * Costs of training
  
- Non-Medical Costs
  * Lost productivity and wages due to dementia-related absenteeism or early retirement.
  * Costs of informal caregiving, including the time and effort spent by family members or friends providing care.
  * Transportation costs<br>
<br>

### **Cost reduction**
- Direct Medical Costs
  * Potential effects on cormorbidities?
- Indirect Medical Costs
  * Costs in specialised patient care or nursing homes
- Indirect Non-Medical Costs
  * Lost productivity and wages due to dementia-related absenteeism or early retirement.
  * Costs of informal caregiving, including the time and effort spent by family members or friends providing care.<br>
<br>


### **Outcomes of interst in cost-effectiveness analyses**
- Disease stage changes and survival
- Cognitive and functional abilities
- Quality of life
- Caregiver burden, stress and quality of life
- QALYs
- Changes in behavioral symptoms (e.g., agitation, aggression)
- Hospitalization rates and lengths of stay
- Utilization of healthcare services
- Changes in patients' ability to engage in daily activities<br>
<br>

### **Potential data sources for cost-effectiveness analyses**
- Published data from clinical trials
- Published data on AD natural history, its associated costs
- Observational studies based on registers and cohorts, etc.<br>
<br>


### **Statistical analyses and parameter specifications**
- Multistate modeling: need real data
- Microsimulation: need to define the population and rules
  * Disease stage and stage-specific health care cost, additional societal cost, utility (quality of life associated with different health states or interventions), mortality
  * Time scale and unit
  * Transition probability of outcomes and adverse event, their hazard ratios
  * Effect-specific QALYs: e.g., 0.8 gains in QALYs per 20% treatment effects??
  
- Output
  * Incremental cost-effectiveness ratios (ICER): difference in cost between two possible interventions (e.g., new intervention vs. standard care), divided by the difference in their effect, usually costs/QALYs
  * Value-based prices=(WTP Threshold) or cost-effectiveness threshold $\times$ (Incremental QALYs); willingess-to-pay (WTP),the maximum amount society is willing to pay for an additional QALY
  * Incremental QALYs = QALYs with New Intervention - QALYs with Comparator or Standard Intervention<br>
<br>



### **Challenges to consider in cost-effectiveness analyses**
- Methodological challenges
  * Extrapolation from RCT results
  * Assumptions of treatment in populations not represented in the clinical trials and treatment adherence
  * Limited data on factors that may influence physician prescribing behavior
  * Account for benefits/harm in terms of comorbidities
  * Rely on published data which may be subject to biases
  * Quantify non-medical costs, e.g., informal care costs
  
- Other considerations
  * Rapid changes in the field, biomarkers, treatments<br>
  * How to determine willingness to pay and cost-effectiveness threshold?<br>
<br>




**Reference:**<br>
1. Jönsson L, Wimo A. Viewpoint: Amyloid-targeting New Therapies for Alzheimer's Disease: A Health Economics Perspective. J Prev Alzheimers Dis. 2023;10(2):349-352.<br>

2. Tahami Monfared AA, Ye W, Sardesai A, Folse H, Chavan A, Kang K, Zhang Q. Estimated Societal Value of Lecanemab in Patients with Early Alzheimer's Disease Using Simulation Modeling. Neurol Ther. 2023 Jun;12(3):795-814.<br>

3. Tahami Monfared AA, Tafazzoli A, Ye W, Chavan A, Zhang Q. Long-Term Health Outcomes of Lecanemab in Patients with Early Alzheimer's Disease Using Simulation Modeling. Neurol Ther. 2022 Jun;11(2):863-880.<br>

4. Rosenthal MB. Novel Alzheimer Disease Treatments and Reconsideration of US Pharmaceutical Reimbursement Policy. JAMA. 2023 Aug 8;330(6):505-506.<br>

5. Tahami Monfared AA, Tafazzoli A, Chavan A, Ye W, Zhang Q. The Potential Economic Value of Lecanemab in Patients with Early Alzheimer's Disease Using Simulation Modeling. Neurol Ther. 2022 Sep;11(3):1285-1307.<br>

6. Tahami Monfared AA, Ye W, Sardesai A, Folse H, Chavan A, Aruffo E, Zhang Q. A Path to Improved Alzheimer's Care: Simulating Long-Term Health Outcomes of Lecanemab in Early Alzheimer's Disease from the CLARITY AD Trial. Neurol Ther. 2023 Jun;12(3):863-881.<br>

7. Igarashi A, Azuma MK, Zhang Q, Ye W, Sardesai A, Folse H, Chavan A, Tomita K, Tahami Monfared AA. Predicting the Societal Value of Lecanemab in Early Alzheimer's Disease in Japan: A Patient-Level Simulation. Neurol Ther. 2023 Aug;12(4):1133-1157.<br>

8. Mattke S, Loh WK, Yuen KH, Yoong J. Preparedness of China's health care system to provide access to a disease-modifying Alzheimer's treatment. Alzheimers Dement. 2023 Jun 6.<br>

9. Belder CRS, Schott JM, Fox NC. Preparing for disease-modifying therapies in Alzheimer's disease. Lancet Neurol. 2023 Sep;22(9):782-783.<br>

10. Bauer K, Schwarzkopf L, Graessel E, Holle R. A claims data-based comparison of comorbidity in individuals with and without dementia. BMC Geriatr. 2014 Jan 28;14:10.


