---
title: "Health economics-introduction"
author:
  - name: Bertil Gustav
date: 2023-09-09
output:
  distill::distill_article:
    self_contained: false
---


```{css, echo = FALSE}
body {
position: relative;
left: -350px;
width: 1800px
}

h1 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}


h3 {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

d-article h3 {
    margin-top: 0.3rem;
    margin-bottom: 0em;
}

ul {
text-indent: 0;
margin: 0px;
padding: -1;
border: 0px;
width: 1200px;
}

p {
text-indent: 0;
padding: -1;
border: 0px;
width: 1200px;
margin-top: 1rem;
}

d-article li {
    margin-top: 0em;
    margin-bottom: 0em;
    margin-left: 0;
    padding-left: 0;
}

d-article p, d-article ul, d-article ol, d-article blockquote {
    margin-top: 1;
    margin-bottom: 0em;
    margin-left: 0;
    margin-right: 0;
}
```


### **Important terms**
- **Base-case analysis**:
- **Quality-adjusted life years (QALYs)**: life year $\times$ health utility weight??
- **Efficacy and effectiveness**: the extent to which an intervention can achieve desired outcome in ideal situation and in reality.<br>
<br>

### **Values of cost-effectiveness analysis**
- Provide data for reimbursement decisions
- Inform treatment guidelines
- Provide pricing benchmark
- Guide subsequent research<br>
<br>






**Reference:**<br>
1. Drummond, M. F., Sculpher, M. J., Claxton, K., Stoddart, G. L., & Torrance, G. W. (2015). Methods for the Economic Evaluation of Health Care Programmes. (4th ed.) Oxford University Press.<br>
2. Ross EL, Weinberg MS, Arnold SE. Cost-effectiveness of Aducanumab and Donanemab for Early Alzheimer Disease in the US. JAMA Neurol. 2022 May 1;79(5):478-487.<br>
3. Cliff ERS, Kelkar AH. Cost-effectiveness of Aducanumab and Donanemab for Early Alzheimer Disease-Estimating the True Value. JAMA Neurol. 2022 Oct 3.<br>
4. Mattke S. Cost-effectiveness of Aducanumab and Donanemab for Early Alzheimer Disease-Estimating the True Value. JAMA Neurol. 2022 Oct 3.<br>
5. Husereau D, Drummond M, Augustovski F, de Bekker-Grob E, Briggs AH, Carswell C, Caulley L, Chaiyakunapruk N, Greenberg D, Loder E, Mauskopf J, Mullins CD, Petrou S, Pwu RF, Staniszewska S; CHEERS 2022 ISPOR Good Research Practices Task Force. Consolidated Health Economic Evaluation Reporting Standards 2022 (CHEERS 2022) Statement: Updated Reporting Guidance for Health Economic Evaluations. Value Health. 2022 Jan;25(1):3-9.

